# These are supported funding model platforms

github: zerforschung
custom: ['https://www.paypal.com/paypalme/radforschung/', 'https://zerforschung.org/unterstuetzen/#finanzielle-unterst%C3%BCtzung']
